<?php

/**
 * Auto generated by prado-cli.php on 2011-03-15 10:33:54.
 */
class AbonosRecord extends TActiveRecord {

    const TABLE = 'abonos';

    public $CodAbono;
    public $FhAbono;
    public $IdTercero;
    public $NrObligacion;
    public $CuentaAbono;
    public $ValorAbono;
    public $CodFormaPago;
    public $CodBanco;
    public $Observaciones;
    public $Saldo;

    public static function finder($className = __CLASS__) {
        return parent::finder($className);
    }

    /**
     * Busca los abonos realizados por un tercero.
     * @param type $IdTercero Codigo del tercero del cual se buscan los abonos
     * @param type $CodObligaicon el numero de la obligacion del tercero
     * @return <Objeto> del tipo AbonosRecord 
     * */
    public static function AbonosTercero($IdTercero, $CodObligacion) {
        $Abonos = new AbonosRecord();
        $Abonos = AbonosRecord::finder()->FindAllBy_IdTercero($IdTercero);
        return $Abonos;
    }

    public static function Transaccion() {

        $Finder = AbonosRecord::finder();
        $Finder->DbConnection->Active = true; //open if necessary
        $Transaction = $Finder->DbConnection->beginTransaction();

        return $Transaction;
    }

//        /**
//         * Busca los abonos realizados por un tercero.
//         * @param type $IdTercero Codigo del tercero del cual se buscan los abonos
//         * @param type $CodObligaicon el numero de la obligacion del tercero
//         * @return <Objeto> del tipo AbonosRecord 
//         **/
//        public static function AbonosTercero($IdTercero,$CodObligacion)
//        {
//            $Abonos  = new AbonosRecord();
//            $Abonos = AbonosRecord::finder()->FindAllBy_IdTercero_AND_CodObligacion($IdTercero,$CodObligacion);
//            return $Abonos;
//        }
}

?>