<?php

/**
 * Auto generated by prado-cli.php on 2011-04-13 06:24:36.
 */
class AcuerdosPagoRecord extends TActiveRecord {

    const TABLE = 'acuerdospago';

    public $CodAcuerdo;
    public $CodObligacion;
    public $CodTarea;
    public $FhAcuerdo;
    public $IdTercero;
    public $PlazoPago;
    public $IdUsuario;
    public $Observaciones;

    public static function finder($className = __CLASS__) {
        return parent::finder($className);
    }

    public static function Transaccion() {

        $Finder = AcuerdosPagoRecord::finder();
        $Finder->DbConnection->Active = true; //open if necessary
        $Transaction = $Finder->DbConnection->beginTransaction();

        return $Transaction;
    }

}

?>