<?php

/**
 * Auto generated by prado-cli.php on 2011-02-09 07:54:57.
 */
class CampanasRecord extends TActiveRecord {
    const TABLE='campanas';

    public $IdCampana;
    public $NombreCampana;
    public $Descripcion;
    public $Usuario;
    public $FhCreacion;
    public $Inactiva;
    public $FhInactiva;

    public static function finder($className=__CLASS__) {
        return parent::finder($className);
    }

    /**
     * Devuelve un objeto con los datos de una campaña especificada consultada
     * por codigo
     * @param  integer $CodCampana El codigo de la campaña a consultar
     * @return Objeto Objeto con los datos de una campaña
     **/
    public static function ObtenerCampana($CodCampana) {
        $Campana = new CampanasRecord();
        $Campana = CampanasRecord::finder()->findByPk($CodCampana);

        return $Campana;
    }
    
      /**
     * Obtiene los datos de una campaña buscado por nombre
     * @param string $Nombre 
     * @return objeto Objeto del tipo CampaniasRecord con los datos de las 
     * campañas que coinciden con el parametro de busqueda
     **/
    public static function ObtenerCampaniaXParametros($Nombre)
    {
        $sql = "SELECT IdCampana, NombreCampana, Descripcion, FhCreacion, Inactiva
                FROM campanas WHERE NombreCampana LIKE  '%" . $Nombre . "%'";
        
        $Campana = new CampanasRecord();
        $Campana = CampanasRecord::finder()->findAllBySql($sql);
        
        return $Campana;
    }
  
    /**
     * Devuelve un objeto con todas las campañas almacenadas
     * @return objeto Objeto con todas los datos de las campañas almacenadas.
     **/
    public static function ObtenerCampanas()
    {
        $Campanas = new CampanasRecord();
        $Campanas = CampanasRecord::finder()->findAll();
        
        return $Campanas;
    }
    
    public static function Transaccion() {

        $Finder = CampanasRecord::finder();
        $Finder->DbConnection->Active = true; //open if necessary
        $Transaction = $Finder->DbConnection->beginTransaction();

        return $Transaction;
    }
}

?>