<?php

/**
 * Auto generated by prado-cli.php on 2011-03-05 10:31:18.
 */
class CiudadesRecord extends TActiveRecord {
    const TABLE='ciudades';

    public $CodCiudad;
    public $NmCiudad;
    public $CodDepartamento;
    public static $RELATIONS = array(
        'Departamentos' => array(self::BELONGS_TO, 'DepartamentosRecord', 'CodDepartamento'),
    );

    public static function finder($className=__CLASS__) {
        return parent::finder($className);
    }

    /**
     * Obtiene la informacion de una ciudad enviada por parametro
     * @param <int> Codigo de ciudad
     * @return <objeto> del tipo CiudadesRecord 
     **/
    public static function ObtenerCiudad($CodCiudad) {
        $Ciudad = new CiudadesRecord();
        $Ciudad = CiudadesRecord::finder()->findByPk($CodCiudad);

        return $Ciudad;
    }
    
    /**
     * Obtiene los datos de una ciudad por nombre
     * @param type $Nombre 
     * @return <objeto> del tipo CiudadesRecord
     **/
    public static function ObtenerCiudadesXParametros($Nombre)
    {
        $sql = "SELECT CodCiudad, NmCiudad, CodDepartamento
                FROM ciudades
                WHERE NmCiudad LIKE '%" . $Nombre ."%'";
        
        $Ciudad = new CiudadesRecord();
        $Ciudad = CiudadesRecord::finder()->With_Departamentos()->findAllBySql($sql);
        
        return $Ciudad;
    }
    
    public static function Transaccion() {

        $Finder = CiudadesRecord::finder();
        $Finder->DbConnection->Active = true; //open if necessary
        $Transaction = $Finder->DbConnection->beginTransaction();

        return $Transaction;
}
}

?>