<?php

/**
 * Auto generated by prado-cli.php on 2011-03-05 10:31:33.
 */
class DepartamentosRecord extends TActiveRecord {
    const TABLE='departamentos';

    public $CodDepartamento;
    public $NmDepartamento;

    public static function finder($className=__CLASS__) {
        return parent::finder($className);
    }

    /**
     * Obtiene los datos de una ciudad por nombre
     * @param type $Nombre 
     * @return <objeto> del tipo DepartamentosRecord
     **/
    public static function ObtenerDepartamentosXParametros($Nombre) {
        $sql = "SELECT CodDepartamento, NmDepartamento
                FROM departamentos
                WHERE NmDepartamento LIKE '%" . $Nombre . "%'";

        $Departamento = new DepartamentosRecord();
        $Departamento = DepartamentosRecord::finder()->findAllBySql($sql);

        return $Departamento;
    }
    
    public static function Transaccion() {

        $Finder = DepartamentosRecord::finder();
        $Finder->DbConnection->Active = true; //open if necessary
        $Transaction = $Finder->DbConnection->beginTransaction();

        return $Transaction;
    }
}

?>