<?php
/**
 * Auto generated by prado-cli.php on 2011-03-21 05:32:21.
 */
class FormasPagoRecord extends TActiveRecord
{
	const TABLE='formaspago';

	public $CodFormaPago;
	public $NmFormaPago;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>