<?php

/**
 * Auto generated by prado-cli.php on 2012-01-27 05:38:03.
 */
class GestionRecord extends TActiveRecord {

    const TABLE = 'gestion';

    public $CodGestion;
    public $CodConceptoGestion;
    public $NroObligacion;
    public $FechaGestion;
    public $CodObligacion;
    public $CodTarea;
    public $CodTercero;
    public $Observaciones;
    public $Usuario;
    public $Telefono;
    public $TiempoGrabado;
    
    public static $RELATIONS = array(
        'Tercero' => array(self::BELONGS_TO, 'TercerosRecord', 'CodTercero'),
        'ConceptoCobranza' => array(self::BELONGS_TO, 'ConceptosCobranzaRecord', 'CodConceptoGestion'),
        'CodObligacion' => array(self::BELONGS_TO, 'ObligacionesRecord', 'CodObligacion'),
    );

    public static function finder($className = __CLASS__) {
        return parent::finder($className);
    }

    /**
     * @param type $CodTercero
     * @return objeto El registro de gestion que se le ha hecho a un moroso 
     * */
    public static function DevGestionXMoroso($CodObligacion) {
        $Gestion = new GestionRecord();
        $sql = "SELECT gestion.* FROM gestion WHERE CodObligacion = $CodObligacion ORDER BY FechaGestion DESC";
        $Gestion = GestionRecord::finder()->With_ConceptoCobranza()->findAllBySql($sql);//By_CodObligacion_AND_CodTercero($CodObligacion,$CodTercero);

        return $Gestion;
    }
    
    public static function ObtenerCarteraTotal()
    {
        $sql="select sum(Saldo) as Cartera from obligaciones;";
        
        $Gestion = new GestionRecord();
        
        $Gestion= GestionRecord::finder('GestionExtRecord')->findAllBySql($sql);
        return $Gestion;
    }
    
    
    public static function InformeGestion()
    {
        
        $sql='  
               SELECT  terceros.NombreExtendido, 
               conceptoscobranza.Descripcion , 
               obligaciones.Saldo 
               
               FROM gestion
               inner join obligaciones on obligaciones.CodObligacion= gestion.CodObligacion
               inner join terceros on terceros.Identificacion= gestion.CodTercero
               inner join conceptoscobranza on conceptoscobranza.CodConcepto= gestion.CodConceptoGestion';
        
        $Gestion= new GestionRecord();
        $Gestion=  GestionRecord::finder('GestionExtRecord')->findAllBySql($sql);
        return $Gestion;
    
    }

    public static function Transaccion() {

        $Finder = GestionRecord::finder();
        $Finder->DbConnection->Active = true; //open if necessary
        $Transaction = $Finder->DbConnection->beginTransaction();

        return $Transaction;
    }

}

class GestionExtRecord extends GestionRecord {

    public $NombreExtendido;
    public $Descripcion;
    public $Saldo;
    public $Cartera;

}

?>