<?php
/**
 * Auto generated by prado-cli.php on 2011-07-24 07:34:27.
 */
class PermisosCrudRecord extends TActiveRecord
{
	const TABLE='permisosespecialescrud';

	public $CodRol;
	public $CodPermisoEspecial;
	public $Ver;
	public $Crear;
	public $Editar;
	public $Eliminar;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>