<?php

/**
 * Auto generated by prado-cli.php on 2011-07-24 06:04:00.
 */
class RolesRecord extends TActiveRecord {
    const TABLE='roles';

    public $CodRol;
    public $NmRol;

    public static function finder($className=__CLASS__) {
        return parent::finder($className);
    }

    public static function ObtenerRoles($Nombre) {
        $sql = "SELECT CodRol, NmRol
                FROM roles
                WHERE NmRol LIKE '%" . $Nombre . "%'";

        $Rol = new RolesRecord();
        $Rol = RolesRecord::finder()->findAllBySql($sql);

        return $Rol;
    }

}

?>