<?php

/**
 * Auto generated by prado-cli.php on 2012-07-29 06:18:35.
 */
class SubConceptosCobranzaRecord extends TActiveRecord {

    const TABLE = 'subconceptoscobranza';

    public $CodSubConcepto;
    public $CodConcepto;
    public $Descripcion;

    public static function finder($className = __CLASS__) {
        return parent::finder($className);
    }

    /**
     * Devuelve un objeto con los subconceptos de gestion.

     * @return Objeto con todos los conceptos de gestion de cobranza
     * */
    public static function getSubConceptosGestion() {
        $sql = "SELECT CodSubConcepto, Descripcion FROM subconceptoscobranza ORDER BY Descripcion ASC";

        $SubConceptos = new SubConceptosCobranzaRecord();
        $SubConceptos = SubConceptosCobranzaRecord::finder()->findAllBySql($sql);

        return $SubConceptos;
    }

}

?>