<?php
/**
 * Auto generated by prado-cli.php on 2011-02-08 09:33:48.
 **/
class UsuariosRecord extends TActiveRecord
{
	const TABLE='usuarios';

	public $Usuario;
	public $Contrasena;
	public $Tipo;
	public $Nombres;
	public $Apellidos;
	public $Notificaciones;
	public $Correos;
	public $Telefono1;
	public $Telefono2;
        public $Direccion;
        public $Gestor;
        public $Administrador;
	public $Inactivo;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
        
    /** 
     * Retorna los datos de un usuario buscado por PK
     * @param  <integer> Numero identificacion de una persona
     * @return <Objeto> Usuario  
     **/
    public static function ObtenerUsuario($Usuario) {
        $Usaurio = new UsuariosRecord();
        
        $Usuario = UsuariosRecord::finder()->findByPk($Usuario);

        return $Usuario;
    }
    
    /**
     * Devuelve todos los usuarios almacenados en la base de datos
     * @return <objeto> del tipo usuariosRecord 
     **/
    public static function Usuarios()
    {
        $Usuarios = new UsuariosRecord();
        $Usuarios = UsuariosRecord::finder()->FindAll();
        
        return $Usuarios;
    }
    
    /**
     * Obtiene los datos de un usuario buscado por nombre o por 
     * apellidos
     * @param type $Nombre 
     * @return <objeto> del tipo UsuariosRecord
     **/
    public static function ObtenerUsuariosXParametros($Nombre)
    {
        $sql = "SELECT Usuario, Nombres, Apellidos, Telefono1, Telefono2, Direccion
                FROM usuarios WHERE Nombres LIKE  '%" . $Nombre . "%' OR Apellidos LIKE '% " . $Nombre . "%'";
        
        $Usuario = new UsuariosRecord();
        $Usuario = UsuariosRecord::finder()->findAllBySql($sql);
        
        return $Usuario;
    }
    
    /**
     * Devuelve todos los usuarios de tipo 2 => gestores
     * @return <objeto> Objeto del tipo usuariosRecord
     **/
    public static function ObtenerGestores()
    {
        $Usuarios = new UsuariosRecord();
        $Usuarios = UsuariosRecord::finder()->FindAll("Tipo = ?",2);
        
        return $Usuarios;
    }
    
    public static function Transaccion() {

        $Finder = UsuariosRecord::finder();
        $Finder->DbConnection->Active = true; //open if necessary
        $Transaction = $Finder->DbConnection->beginTransaction();

        return $Transaction;
    }
}
?>